#!/bin/bash

set -e

DATABASE_PROPERTIES=~/.BuildServer/config/database.properties

mkdir -p $(dirname $DATABASE_PROPERTIES)
if [[ ! -e $DATABASE_PROPERTIES ]]; then
    cat > $DATABASE_PROPERTIES <<EOF
connectionProperties.user=teamcity
connectionUrl=jdbc\\:postgresql\\://${POSTGRESQL_PORT_5432_TCP_ADDR}/
EOF
fi

/TeamCity/bin/teamcity-server.sh run
