#!/bin/bash

set -e

DATABASE_PROPERTIES=~/.BuildServer/config/database.properties

mkdir -p $(dirname $DATABASE_PROPERTIES)
if [[ ! -e $DATABASE_PROPERTIES ]]; then
    echo 'connectionUrl=jdbc\:hsqldb\:file\:$TEAMCITY_SYSTEM_PATH/buildserver' > $DATABASE_PROPERTIES
fi

/TeamCity/bin/teamcity-server.sh run
