FROM java:8

RUN mkdir -p /root/.BuildServer/plugins
ADD http://teamcity.jetbrains.com/guestAuth/repository/download/bt398/lastest.lastSuccessful/teamcity.github.zip /root/.BuildServer/plugins/teamcity.github.zip
